//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRSPKT_Apps.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRSPKT_Apps.Resources.ru", typeof(ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квартирография.
        /// </summary>
        internal static string apartCalc_button_name {
            get {
                return ResourceManager.GetString("apartCalc_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подсчет квартирографии для текущего вида.
        /// </summary>
        internal static string apartCalc_toolTip {
            get {
                return ResourceManager.GetString("apartCalc_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переименовать помещения.
        /// </summary>
        internal static string apartRoomRename_button_name {
            get {
                return ResourceManager.GetString("apartRoomRename_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переименовать помещения квартиры на текущем виде.
        /// </summary>
        internal static string apartRoomRename_toolTip {
            get {
                return ResourceManager.GetString("apartRoomRename_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размеры в осях.
        /// </summary>
        internal static string dimAxies_button_name {
            get {
                return ResourceManager.GetString("dimAxies_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проставить размеры в осях.
        /// </summary>
        internal static string dimAxies_toolTip {
            get {
                return ResourceManager.GetString("dimAxies_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полы.
        /// </summary>
        internal static string floorfinish_button_name {
            get {
                return ResourceManager.GetString("floorfinish_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание отделочных полов.
        /// </summary>
        internal static string floorfinish_toolTip {
            get {
                return ResourceManager.GetString("floorfinish_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все помещения.
        /// </summary>
        internal static string floorFinishes_all_rooms_radio {
            get {
                return ResourceManager.GetString("floorFinishes_all_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень пола.
        /// </summary>
        internal static string floorFinishes_groupboxName {
            get {
                return ResourceManager.GetString("floorFinishes_groupboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По значению.
        /// </summary>
        internal static string floorFinishes_height_label {
            get {
                return ResourceManager.GetString("floorFinishes_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По параметру.
        /// </summary>
        internal static string floorFinishes_height_param_label {
            get {
                return ResourceManager.GetString("floorFinishes_height_param_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите значение уровня пола.
        /// </summary>
        internal static string floorFinishes_heightValueError {
            get {
                return ResourceManager.GetString("floorFinishes_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помещений нет в проекте.
        /// </summary>
        internal static string floorFinishes_noRoomError {
            get {
                return ResourceManager.GetString("floorFinishes_noRoomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PRSPKT_Apps.
        /// </summary>
        internal static string floorFinishes_ribbon_panel_name {
            get {
                return ResourceManager.GetString("floorFinishes_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тип пола:.
        /// </summary>
        internal static string floorFinishes_select_floor_label {
            get {
                return ResourceManager.GetString("floorFinishes_select_floor_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранные помещения.
        /// </summary>
        internal static string floorFinishes_SelectedRooms {
            get {
                return ResourceManager.GetString("floorFinishes_SelectedRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание полов.
        /// </summary>
        internal static string floorFinishes_TaskDialogName {
            get {
                return ResourceManager.GetString("floorFinishes_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отделочные полы.
        /// </summary>
        internal static string floorFinishes_transactionName {
            get {
                return ResourceManager.GetString("floorFinishes_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция прервана по неизвестным причинам..
        /// </summary>
        internal static string floorFinishes_unexpectedError {
            get {
                return ResourceManager.GetString("floorFinishes_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom Elevation Max.
        /// </summary>
        internal static string levelTag_bottom_elevation_max {
            get {
                return ResourceManager.GetString("levelTag_bottom_elevation_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom Elevation Min.
        /// </summary>
        internal static string levelTag_bottom_elevation_min {
            get {
                return ResourceManager.GetString("levelTag_bottom_elevation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень.
        /// </summary>
        internal static string levelTag_parameter_group {
            get {
                return ResourceManager.GetString("levelTag_parameter_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top Elevation Max.
        /// </summary>
        internal static string levelTag_top_elevation_max {
            get {
                return ResourceManager.GetString("levelTag_top_elevation_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top Elevation Min.
        /// </summary>
        internal static string levelTag_top_elevation_min {
            get {
                return ResourceManager.GetString("levelTag_top_elevation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все помещения на текущем виде.
        /// </summary>
        internal static string roomFinishes_all_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_all_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота отделочного слоя.
        /// </summary>
        internal static string roomFinishes_board_height_label {
            get {
                return ResourceManager.GetString("roomFinishes_board_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отделочная стена.
        /// </summary>
        internal static string roomFinishes_button_name {
            get {
                return ResourceManager.GetString("roomFinishes_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string roomFinishes_Cancel_Button {
            get {
                return ResourceManager.GetString("roomFinishes_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите высоту отделочной слоя (стены):.
        /// </summary>
        internal static string roomFinishes_heightValueError {
            get {
                return ResourceManager.GetString("roomFinishes_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединить стены.
        /// </summary>
        internal static string roomFinishes_joinWalls {
            get {
                return ResourceManager.GetString("roomFinishes_joinWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string roomFinishes_OK_Button {
            get {
                return ResourceManager.GetString("roomFinishes_OK_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помещения.
        /// </summary>
        internal static string roomFinishes_ribbon_panel_name {
            get {
                return ResourceManager.GetString("roomFinishes_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тип отделки:.
        /// </summary>
        internal static string roomFinishes_select_wall_label {
            get {
                return ResourceManager.GetString("roomFinishes_select_wall_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранные помещения.
        /// </summary>
        internal static string roomFinishes_selected_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_selected_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор помещений.
        /// </summary>
        internal static string roomFinishes_SelectRooms {
            get {
                return ResourceManager.GetString("roomFinishes_SelectRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание отделки.
        /// </summary>
        internal static string roomFinishes_TaskDialogName {
            get {
                return ResourceManager.GetString("roomFinishes_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание отделки.
        /// </summary>
        internal static string roomFinishes_toolTip {
            get {
                return ResourceManager.GetString("roomFinishes_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание отделочный стен.
        /// </summary>
        internal static string roomFinishes_transactionName {
            get {
                return ResourceManager.GetString("roomFinishes_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция прервана по неизвестным причинам..
        /// </summary>
        internal static string roomFinishes_unexpectedError {
            get {
                return ResourceManager.GetString("roomFinishes_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция не будет работать с этим типом стены (Vertically compound structure)..
        /// </summary>
        internal static string roomFinishes_verticalCompoundError {
            get {
                return ResourceManager.GetString("roomFinishes_verticalCompoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструментики.
        /// </summary>
        internal static string tools_ribbon_panel_name {
            get {
                return ResourceManager.GetString("tools_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма длин.
        /// </summary>
        internal static string totalLength_button_name {
            get {
                return ResourceManager.GetString("totalLength_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подсчет общей длины линий.
        /// </summary>
        internal static string totalLength_toolTip {
            get {
                return ResourceManager.GetString("totalLength_toolTip", resourceCulture);
            }
        }
    }
}
